### ISSUE TITLE
Run in remote server

### ISSUE THREAD

**Issue by ZeitgeberH** [musyoku/chainer-gqn#6]
Hi,
Thanks for your repo! 
I am trying to run your code on a remote server. It seems there is some issue related to X11 forwarding and GL rendering. Is it possible to run the code in a headless mode (without creating the window).

``python create_dataset.py 
Error 65544: X11: RandR gamma ramp support seems broken
Error 65542: GLX: GLX version 1.3 is required
Traceback (most recent call last):
  File "create_dataset.py", line 104, in <module>
    main()
  File "create_dataset.py", line 33, in main
    renderer = gqn.three.Renderer(screen_size[0], screen_size[1])
RuntimeError: Failed to initialize GLFW.

**Comment by musyoku** [comment]
Hi.
The renderer is currently under development and still needs shading, headless mode, wall texture, etc.
I will support them.

**Comment by shuqinlee** [comment]
Hi, 
Thanks for your code. I met the same problem. Is there a way to solve this? or could you provide some solutions to it (no need to implement it now)

**Comment by musyoku** [comment]
Hi.
I created [gqn-datasets-translator](https://github.com/musyoku/gqn-datasets-translator).

**Comment by musyoku** [comment]
Hi.
I am developing a new renderer.
https://github.com/musyoku/gqn-dataset-renderer
